from .courts import Court
from .courts_schema_types_autogenerated import RawCourt, RawCourtRepository


class CourtFactory(Court):
    def __init__(self, data):
        data = make_court_valid(data)
        super().__init__(data)


def make_court_valid(data) -> RawCourt:
    for keyword in ["code", "name", "link"]:
        if keyword not in data:
            data[keyword] = f"placeholder {keyword}"
    for keyword in ["selectable", "listable"]:
        if keyword not in data:
            data[keyword] = True
    return data


def make_court_repo_valid(data) -> RawCourtRepository:
    new_court_groups = []
    for court_group in data:
        new_courts = []
        for court in court_group["courts"]:
            new_courts.append(make_court_valid(court))
        court_group["court"] = new_courts
        new_court_groups.append(court_group)
    return new_court_groups
